apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowise-deployment
  labels:
      app: flowise-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowise-app
  template:
    metadata:
      labels:
        app: flowise-app
    spec:
      containers:
      - name: flowise-container
        image: flowise:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_TYPE
          value: 'postgres'
        - name: DATABASE_HOST
          value: 'postgres-service'
        - name: DATABASE_PORT
          value: '5432'  
        - name: DATABASE_NAME
          value: 'flowise'
        - name: DATABASE_USER
          value: 'postgres' 
        - name: DATABASE_PASSWORD 
          valueFrom:
            secretKeyRef: 
              name: db-secrets
              key: db_password
        - name: DATABASE_SSL
          value: 'false'  
        # - name: DATABASE_SSL_KEY_BASE64
        #   value: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRvQ0NRREpiWm9mb3NpZXpUQU5CZ2txaGtpRzl3MEJBUXNGQURBN01Rc3dDUVlEVlFRR0V3SmgKZFRFTU1Bb0dBMVVFQ0F3RGJuTjNNUTh3RFFZRFZRUUhEQVp6ZVdSdVpYa3hEVEFMQmdOVkJBb01CR1p6WVdrdwpIaGNOTWpVd01qRXlNRFV3TkRBMldoY05Nall3TWpFeU1EVXdOREEyV2pBN01Rc3dDUVlEVlFRR0V3SmhkVEVNCk1Bb0dBMVVFQ0F3RGJuTjNNUTh3RFFZRFZRUUhEQVp6ZVdSdVpYa3hEVEFMQmdOVkJBb01CR1p6WVdrd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFERlNucXZjVFBuK1NmMnRweHlxRllseStHZwp2SkR5a05CY1RNZjRKYlk0M2J5OUI5S3k4M1lReE1rVFBrcVNMZW9yNFZxMjdJWGNiVjl0M1FEcHNrUHYzZVFNClBqOGw4eG1EZE5laXp3TVR1QkVLN2FYMHY4K2ViVlUweVJGckVEQjJYTVJLbjRHcm9YSEQ1NDZhNUpIUzA0dXEKanZiSUNsSjBYbG9aSjUzd1dXRDd2UVcxM3VBc0xVbS9NSit3TnB3eXB3QjhBeEQySlpPdEhZQzFlNTdlSFg5VgordEVRRkRwd0pzN1V4RTRMNGM0d1hqRC9HVlZTMytlc01wUUNYWldPWm5raEZHQW1Ha3piTWRUWVc3SkwzK1U1Ck5zY1lXQVVzWGZ4ZWNIYVJVUjVqUGR4YlkwamdWdjZORkp1Tjc1TXFwOElON0hyeUdGZVk0V2pLZjFSTkFnTUIKQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCMjZnalU5LzBhcUtGc0pXWFhRUzBiTys5a24wWWFFZUdPWApGUDh6V1VtZGxVMDF1dzFyNFdaTWF0MGRwZnhRV1ZYUXJzYzM1RTl3M3JpYVFQY29TRGRzS2dCZFdCWGo5ZzFKClVaVlBkM1UvOHRoc1RObFdUcTVlS1dkcmVDV3cyb2lnNFZuUDFqRER4S0RwVGxJU0UyZXdDbmJsVkdpcFJoRXUKV25PcENYeUdDNWIyWkNPaWNkMGFRVisxNWtMV0Y1a2dBZU1kKzF0ODZVUDAwaUxhV2p0R2NDTG5xY3Q1Wm43cAp6VmhWV3VlNlQybUJIM3NLaW9KSjBUMmc2TmNnZGJiQ1lOa0ovR1EwTEo3dDNxTjg5TncycHRXakQ5andOMjRQCitEQ1Y3ZElOcDVQTnB5dVR0TGpxNEUvUEhVZW44T3lHTWZlNitEbGt5S2VOcmJ4OCtqZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo='
---
apiVersion: v1
kind: Service
metadata:
  name: flowise-service
  labels:
    app: flowise-app
spec:
  type: NodePort
  selector:
    app: flowise-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001

# kubectl port-forward svc/flowise-service 8080:80
      
